import = [
  "~/.config/alacritty/themes/everforest_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 7.0

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[window]
# opacity = 0.94
padding= {x= 10, y= 10}
